import image from "./../../../assets/images/profile.jpg";

export const employees = [
    {
        _id: 1,
        firstName: 'Inigo',
        lastName: 'Lopez',
        department: {name: 'Engineering'},
        role: {name: 'Frontend'},
        rank: {name: 'Senior'},
        image,
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux', 'Testing'],
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
        dateJoined: new Date(2022, 5, 1),
        gender: 'Male',
        email: 'inigo.lopez@oyster.com',
        birthDate: new Date(1993, 7, 29),
        phone: '+233270048319',
        emergencyPhone: '+233555180048'
    },
    {
        _id: 2,
        firstName: 'Stanley',
        lastName: 'Hayford',
        department: {name: 'Engineering'},
        role: {name: 'Frontend'},
        rank: {name: 'Senior'},
        image,
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux', 'Testing'],
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
        dateJoined: new Date(2022, 5, 1),
        gender: 'Male',
        email: 'stanley.hayford@oyster.com',
        birthDate: new Date(1993, 7, 29),
        phone: '+233270048319',
        emergencyPhone: '+233555180048'
    },
    {
        _id: 3,
        firstName: 'Antoinette',
        lastName: 'Dewortor',
        department: {name: 'Engineering'},
        role: {name: 'Frontend'},
        rank: {name: 'Senior'},
        image,
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux', 'Testing'],
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
        dateJoined: new Date(2022, 5, 1),
        gender: 'Female',
        email: 'antoinette.dewortor@oyster.com',
        birthDate: new Date(1993, 7, 29),
        phone: '+233270048319',
        emergencyPhone: '+233555180048'
    },
    {
        _id: 4,
        firstName: 'Gigi',
        lastName: 'Stone',
        department: {name: 'Engineering'},
        role: {name: 'Frontend'},
        rank: {name: 'Senior'},
        image,
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux', 'Testing'],
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
        dateJoined: new Date(2022, 5, 1),
        gender: 'Male',
        email: 'inigo.lopez@oyster.com',
        birthDate: new Date(1993, 7, 29),
        phone: '+233270048319',
        emergencyPhone: '+233555180048'
    },
    {
        _id: 5,
        firstName: 'Stanley',
        lastName: 'Hayford',
        department: {name: 'Engineering'},
        role: {name: 'Frontend'},
        rank: {name: 'Senior'},
        image,
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux', 'Testing'],
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
        dateJoined: new Date(2022, 5, 1),
        gender: 'Male',
        email: 'stanley.hayford@oyster.com',
        birthDate: new Date(1993, 7, 29),
        phone: '+233270048319',
        emergencyPhone: '+233555180048'
    },
    {
        _id: 6,
        firstName: 'Antoinette',
        lastName: 'Dewortor',
        department: {name: 'Engineering'},
        role: {name: 'Frontend'},
        rank: {name: 'Senior'},
        image,
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux', 'Testing'],
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
        dateJoined: new Date(2022, 5, 1),
        gender: 'Female',
        email: 'antoinette.dewortor@oyster.com',
        birthDate: new Date(1993, 7, 29),
        phone: '+233270048319',
        emergencyPhone: '+233555180048'
    }
]