// const BASE_URL = 'http://localhost:8000/api/v1';
const BASE_URL = 'https://employees-oyster.herokuapp.com/api/v1';
const OYSTER_EMPLOYEE_MANAGEMENT_THEME_VARIANT = 'OYSTER_EMPLOYEE_MANAGEMENT_THEME_VARIANT';
const OYSTER_EMPLOYEE_MANAGEMENT_VIEW_MODE = 'OYSTER_EMPLOYEE_MANAGEMENT_VIEW_MODE';

export const CONSTANTS = {BASE_URL, OYSTER_EMPLOYEE_MANAGEMENT_VIEW_MODE, OYSTER_EMPLOYEE_MANAGEMENT_THEME_VARIANT};